version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: scam-detection-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      # Uncomment these if you want authentication (recommended for production)
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: scam_detection
    volumes:
      - mongodb_data:/data/db
    networks:
      - scam-detection-network
    # Run as standalone instance (no replica set)
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Optional: MongoDB Express for web-based admin interface
  mongo-express:
    image: mongo-express:1.0.0
    container_name: scam-detection-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      # Uncomment if using authentication
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - scam-detection-network

volumes:
  mongodb_data:
    driver: local

networks:
  scam-detection-network:
    driver: bridge